[providers]
python = "3.11"

[phases.setup]
nixPkgs = ['python311', 'nodejs', 'npm']

[phases.install]
cmds = [
  'npm install',
  'python -m pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = 'python -m flask db upgrade && python start_production.py'
