[phases.setup]
nixPkgs = ['python311', 'nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm install',
  'python3.11 -m pip install --upgrade pip',
  'python3.11 -m pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = 'python3.11 -m flask db upgrade && python3.11 start_production.py'
