[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'python -m flask db upgrade && python start_production.py'
